version: 2
jobs:
  bootstrap-build:
    docker:
      - image: codesmithy/gcc-bootstrap-build-prerequisites:0.14.0
    steps:
      - run: 
          name: "Set NUIME_ROOT environment variables"
          command: echo 'export NUIME_ROOT="/workspace/projects/nuime-build"' >> $BASH_ENV
      - checkout:
          path: /workspace/projects/nuime-build/build-toolchains
      - run:
          name: Build
          command: cd /workspace/projects/nuime-build/build-toolchains/build-files/gnumake && make
      - run:
          name: Test build
          command: cd /workspace/projects/nuime-build/build-toolchains/tests/build-files/gnumake && make
      - run:
          name: Run the tests
          command: cd /workspace/projects/nuime-build/build-toolchains/tests/build-files/gnumake && ./nuime_buildtoolchains_tests
  build:
    docker:
      - image: codesmithy/gcc-build-prerequisites:0.18.0
    steps:
      - run:
          name: "Set NUIME_ROOT environment variables"
          command: echo 'export NUIME_ROOT="/workspace/projects/nuime-build"' >> $BASH_ENV
      - checkout:
          path: /workspace/projects/nuime-build/build-toolchains
      - run:
          name: Build
          command: cd /workspace/projects/nuime-build/build-toolchains/build-files/gnumake && make
      - run:
          name: Test build
          command: cd /workspace/projects/nuime-build/build-toolchains/tests/build-files/gnumake && make
      - run:
          name: Run the tests
          command: cd /workspace/projects/nuime-build/build-toolchains/tests/build-files/gnumake && ./nuime_buildtoolchains_tests
workflows:
  version: 2
  continuous_build:
    jobs:
      - bootstrap-build
      - build
  weekly_build:
    jobs:
      - bootstrap-build
      - build
    triggers:
      - schedule:
          cron: "0 8 * * 0"
          filters:
            branches:
              only:
                 - main
