version: 2
jobs:
  bootstrap-build:
    docker:
      - image: codesmithy/gcc-bootstrap-build-prerequisites:0.12.0
    steps:
      - run: 
          name: "Set CODESMITHYIDE_ROOT environment variables"
          command: echo 'export CODESMITHYIDE_ROOT="/workspace/projects/codesmithyide"' >> $BASH_ENV
      - checkout:
          path: /workspace/projects//codesmithyide/build-toolchains
      - run:
          name: Build
          command: cd /workspace/projects//codesmithyide/build-toolchains/build-files/gnumake && make
      - run:
          name: Test build
          command: cd /workspace/projects//codesmithyide/build-toolchains/tests/build-files/gnumake && make
      - run:
          name: Run the tests
          command: cd /workspace/projects//codesmithyide/build-toolchains/tests/build-files/gnumake && ./CodeSmithyBuildToolchainsTests
  build:
    docker:
      - image: codesmithy/gcc-build-prerequisites:0.16.0
    steps:
      - run:
          name: "Set CODESMITHYIDE_ROOT environment variables"
          command: echo 'export CODESMITHYIDE_ROOT="/workspace/projects//codesmithyide"' >> $BASH_ENV
      - checkout:
          path: /workspace/projects//codesmithyide/build-toolchains
      - run:
          name: Build
          command: cd /workspace/projects//codesmithyide/build-toolchains/build-files/gnumake && make
      - run:
          name: Test build
          command: cd /workspace/projects//codesmithyide/build-toolchains/tests/build-files/gnumake && make
      - run:
          name: Run the tests
          command: cd /workspace/projects//codesmithyide/build-toolchains/tests/build-files/gnumake && ./CodeSmithyBuildToolchainsTests
workflows:
  version: 2
  continuous_build:
    jobs:
      - bootstrap-build
      - build
  weekly_build:
    jobs:
      - bootstrap-build
      - build
    triggers:
      - schedule:
          cron: "0 8 * * 0"
          filters:
            branches:
              only:
                 - main
